version: "3.8"
services:
  netsocket:
    image: strayfade/netsocket:latest
    container_name: netsocket
    ports:
      - 4675:4675
    environment:
      - PORT=4675
      - HOST=0.0.0.0
    restart: always