; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:netsocketWirelessAdapter]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
build_src_filter = -<*.cpp> +<WirelessAdapter.cpp>
monitor_port = COM18
upload_port = COM18
lib_deps = 
	arduino-libraries/Servo@^1.3.0

[env:netsocketOutlet]
platform = espressif32
board = adafruit_qtpy_esp32c3
framework = arduino
monitor_speed = 115200
build_src_filter = -<*.cpp> +<Outlet.cpp>
monitor_port = COM19
upload_port = COM19
lib_deps = 
	arduino-libraries/Servo@^1.3.0

[env:netsocketLock]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
build_src_filter = -<*.cpp> +<Lock.cpp>
lib_deps = 
	arduino-libraries/Servo@^1.3.0
