#!/usr/bin/env bash
# Builds the Netsocket Android notification forwarder APK without Android Studio.
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

TOOLS_DIR="$PROJECT_ROOT/.tools"
DIST_DIR="$PROJECT_ROOT/dist"
GRADLE_VERSION="8.11.1"
GRADLE_HOME="$TOOLS_DIR/gradle-$GRADLE_VERSION"

step() {
  echo ""
  echo "==> $*"
}

find_jdk_home() {
  local candidates=()
  if [[ -n "${JAVA_HOME:-}" && -x "$JAVA_HOME/bin/java" ]]; then
    candidates+=("$JAVA_HOME")
  fi
  candidates+=(
    "/usr/lib/jvm/java-21-openjdk"
    "/usr/lib/jvm/java-21-openjdk-amd64"
    "/usr/lib/jvm/java-17-openjdk"
    "/usr/lib/jvm/java-17-openjdk-amd64"
    "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
    "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
  )

  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -x "$candidate/bin/java" ]]; then
      echo "$candidate"
      return 0
    fi
  done

  echo "JDK 17 or 21 is required. Install one, or set JAVA_HOME." >&2
  exit 1
}

find_android_sdk() {
  local candidates=(
    "${ANDROID_HOME:-}"
    "${ANDROID_SDK_ROOT:-}"
    "$HOME/Library/Android/sdk"
    "$HOME/Android/Sdk"
    "/usr/lib/android-sdk"
  )
  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -n "$candidate" && -d "$candidate/platforms" ]]; then
      echo "$candidate"
      return 0
    fi
  done

  echo "Android SDK not found. Install platforms;android-36 (or set ANDROID_HOME)." >&2
  exit 1
}

ensure_gradle() {
  local gradle_bin="$GRADLE_HOME/bin/gradle"
  if [[ -x "$gradle_bin" ]]; then
    echo "$gradle_bin"
    return 0
  fi

  mkdir -p "$TOOLS_DIR"
  local zip_path="$TOOLS_DIR/gradle-${GRADLE_VERSION}-bin.zip"
  local url="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"

  step "Downloading Gradle ${GRADLE_VERSION}"
  curl -fsSL "$url" -o "$zip_path"

  step "Extracting Gradle"
  unzip -q -o "$zip_path" -d "$TOOLS_DIR"
  rm -f "$zip_path"

  if [[ ! -x "$gradle_bin" ]]; then
    echo "Gradle extraction failed; expected $gradle_bin" >&2
    exit 1
  fi
  echo "$gradle_bin"
}

ensure_wrapper_jar() {
  local wrapper_jar="$PROJECT_ROOT/gradle/wrapper/gradle-wrapper.jar"
  if [[ -f "$wrapper_jar" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$wrapper_jar")"
  step "Downloading gradle-wrapper.jar"
  curl -fsSL \
    "https://github.com/gradle/gradle/raw/v${GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar" \
    -o "$wrapper_jar"
}

step "Resolving JDK"
JAVA_HOME="$(find_jdk_home)"
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"
echo "Using JAVA_HOME=$JAVA_HOME"

step "Resolving Android SDK"
ANDROID_HOME="$(find_android_sdk)"
export ANDROID_HOME
export ANDROID_SDK_ROOT="$ANDROID_HOME"
echo "Using ANDROID_HOME=$ANDROID_HOME"

cat > "$PROJECT_ROOT/local.properties" <<EOF
## Generated by build.sh — do not commit
sdk.dir=${ANDROID_HOME}
EOF

GRADLE_BIN="$(ensure_gradle)"
ensure_wrapper_jar
mkdir -p "$DIST_DIR"

step "Building debug APK"
"$GRADLE_BIN" --no-daemon assembleDebug

BUILT_APK="$PROJECT_ROOT/app/build/outputs/apk/debug/app-debug.apk"
if [[ ! -f "$BUILT_APK" ]]; then
  echo "APK not found at $BUILT_APK" >&2
  exit 1
fi

OUT_APK="$DIST_DIR/netsocket-notifications-debug.apk"
cp -f "$BUILT_APK" "$OUT_APK"

step "Build complete"
echo "APK: $OUT_APK"
echo ""
echo "Install with:"
echo "  adb install -r \"$OUT_APK\""
echo ""
echo "Then open the app, set host/port/secret, enable Notification Access, and allow unrestricted battery."
