#Requires -Version 5.1
<#
.SYNOPSIS
  Builds the Netsocket Android notification forwarder APK without Android Studio.

.DESCRIPTION
  Locates (or downloads) a compatible JDK + Gradle, points at the Android SDK,
  and runs assembleDebug. The installable APK is copied to .\dist\
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectRoot

$ToolsDir = Join-Path $ProjectRoot ".tools"
$DistDir = Join-Path $ProjectRoot "dist"
$GradleVersion = "8.11.1"
$GradleHome = Join-Path $ToolsDir "gradle-$GradleVersion"

function Write-Step([string]$Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Find-JdkHome {
    $candidates = New-Object System.Collections.Generic.List[string]
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\java.exe"))) {
        $candidates.Add($env:JAVA_HOME)
    }

    foreach ($path in @(
        "C:\Program Files\Java\jdk-21.0.11",
        "C:\Program Files\Java\jdk-21",
        "C:\Program Files\Java\jdk-17",
        "C:\Program Files\Eclipse Adoptium",
        "C:\Program Files\Microsoft"
    )) {
        if (Test-Path $path) {
            Get-ChildItem -Path $path -Directory -ErrorAction SilentlyContinue |
                Where-Object { $_.Name -match '^jdk-?(17|21)' -or $_.Name -match '^jdk-17' -or $_.Name -match '^jdk-21' } |
                ForEach-Object { $candidates.Add($_.FullName) }
            if (Test-Path (Join-Path $path "bin\java.exe")) {
                $candidates.Add($path)
            }
        }
    }

    foreach ($candidate in $candidates) {
        $javaExe = Join-Path $candidate "bin\java.exe"
        if (Test-Path $javaExe) {
            return $candidate
        }
    }

    throw "JDK 17 or 21 is required. Install one, or set JAVA_HOME."
}

function Find-AndroidSdk {
    $candidates = @(
        $env:ANDROID_HOME,
        $env:ANDROID_SDK_ROOT,
        (Join-Path $env:LOCALAPPDATA "Android\Sdk"),
        (Join-Path $env:USERPROFILE "AppData\Local\Android\Sdk"),
        "C:\Android\Sdk"
    ) | Where-Object { $_ -and $_.Trim() -ne "" }

    foreach ($candidate in $candidates) {
        if (Test-Path (Join-Path $candidate "platforms")) {
            return (Resolve-Path $candidate).Path
        }
    }

    throw "Android SDK not found. Install platform-tools + platforms;android-36 (or set ANDROID_HOME)."
}

function Ensure-Gradle {
    $gradleBat = Join-Path $GradleHome "bin\gradle.bat"
    if (Test-Path $gradleBat) {
        return $gradleBat
    }

    New-Item -ItemType Directory -Force -Path $ToolsDir | Out-Null
    $zipPath = Join-Path $ToolsDir "gradle-$GradleVersion-bin.zip"
    $url = "https://services.gradle.org/distributions/gradle-$GradleVersion-bin.zip"

    Write-Step "Downloading Gradle $GradleVersion"
    Invoke-WebRequest -Uri $url -OutFile $zipPath

    Write-Step "Extracting Gradle"
    Expand-Archive -Path $zipPath -DestinationPath $ToolsDir -Force
    Remove-Item $zipPath -Force -ErrorAction SilentlyContinue

    if (-not (Test-Path $gradleBat)) {
        throw "Gradle extraction failed; expected $gradleBat"
    }
    return $gradleBat
}

function Ensure-WrapperJar {
    $wrapperJar = Join-Path $ProjectRoot "gradle\wrapper\gradle-wrapper.jar"
    if (Test-Path $wrapperJar) {
        return
    }

    New-Item -ItemType Directory -Force -Path (Split-Path $wrapperJar) | Out-Null
    Write-Step "Downloading gradle-wrapper.jar"
    # Official wrapper jar from the Gradle GitHub release matching our distribution.
    $url = "https://github.com/gradle/gradle/raw/v$GradleVersion/gradle/wrapper/gradle-wrapper.jar"
    Invoke-WebRequest -Uri $url -OutFile $wrapperJar
}

Write-Step "Resolving JDK"
$jdkHome = Find-JdkHome
$env:JAVA_HOME = $jdkHome
$env:PATH = "$(Join-Path $jdkHome 'bin');$env:PATH"
Write-Host "Using JAVA_HOME=$jdkHome"

Write-Step "Resolving Android SDK"
$sdkPath = Find-AndroidSdk
$env:ANDROID_HOME = $sdkPath
$env:ANDROID_SDK_ROOT = $sdkPath
Write-Host "Using ANDROID_HOME=$sdkPath"

$sdkDirForProps = $sdkPath -replace '\\', '/'
@"
## Generated by build.ps1 — do not commit
sdk.dir=$sdkDirForProps
"@ | Set-Content -Path (Join-Path $ProjectRoot "local.properties") -Encoding ASCII

$gradleBat = Ensure-Gradle
Ensure-WrapperJar

New-Item -ItemType Directory -Force -Path $DistDir | Out-Null

Write-Step "Building debug APK"
& $gradleBat "--no-daemon" "assembleDebug"
if ($LASTEXITCODE -ne 0) {
    throw "Gradle build failed with exit code $LASTEXITCODE"
}

$builtApk = Join-Path $ProjectRoot "app\build\outputs\apk\debug\app-debug.apk"
if (-not (Test-Path $builtApk)) {
    throw "APK not found at $builtApk"
}

$outApk = Join-Path $DistDir "netsocket-notifications-debug.apk"
Copy-Item -Force $builtApk $outApk

Write-Step "Build complete"
Write-Host "APK: $outApk"
Write-Host ""
Write-Host "Install with:"
Write-Host "  adb install -r `"$outApk`""
Write-Host ""
Write-Host "Then open the app, open Settings, set host + Command Palette secret, enable Notification Access if forwarding, and allow unrestricted battery."
