@echo off
rem Builds the Netsocket Android notification forwarder APK and installs it
rem over ADB. Mirrors build.ps1 (JDK + SDK resolution, assembleDebug) and
rem then runs `adb install -r` against the first connected device.
setlocal EnableDelayedExpansion

set "PROJECT_ROOT=%~dp0"
cd /d "%PROJECT_ROOT%"

echo.
echo ==^> Resolving JDK
set "JDK_HOME="
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" set "JDK_HOME=%JAVA_HOME%"
if not defined JDK_HOME if exist "%LOCALAPPDATA%\Java\jdk-17\bin\java.exe" set "JDK_HOME=%LOCALAPPDATA%\Java\jdk-17"
if not defined JDK_HOME if exist "C:\Program Files\Java\jdk-17\bin\java.exe" set "JDK_HOME=C:\Program Files\Java\jdk-17"
if not defined JDK_HOME if exist "C:\Program Files\Java\jdk-21\bin\java.exe" set "JDK_HOME=C:\Program Files\Java\jdk-21"
if not defined JDK_HOME (
    echo JDK 17 or 21 is required. Install one, or set JAVA_HOME.
    exit /b 1
)
set "JAVA_HOME=%JDK_HOME%"
set "PATH=%JDK_HOME%\bin;%PATH%"
echo Using JAVA_HOME=%JDK_HOME%

echo.
echo ==^> Resolving Android SDK
set "SDK_PATH="
if defined ANDROID_HOME if exist "%ANDROID_HOME%\platforms" set "SDK_PATH=%ANDROID_HOME%"
if not defined SDK_PATH if defined ANDROID_SDK_ROOT if exist "%ANDROID_SDK_ROOT%\platforms" set "SDK_PATH=%ANDROID_SDK_ROOT%"
if not defined SDK_PATH if exist "%LOCALAPPDATA%\Android\Sdk\platforms" set "SDK_PATH=%LOCALAPPDATA%\Android\Sdk"
if not defined SDK_PATH (
    echo Android SDK not found. Install platform-tools + platforms;android-36 ^(or set ANDROID_HOME^).
    exit /b 1
)
set "ANDROID_HOME=%SDK_PATH%"
set "ANDROID_SDK_ROOT=%SDK_PATH%"
echo Using ANDROID_HOME=%SDK_PATH%

rem local.properties is gitignored (see .gitignore).
set "SDK_PROPS=%SDK_PATH:\=/%"
(
    echo ## Generated by build.bat -- do not commit
    echo sdk.dir=%SDK_PROPS%
) > "%PROJECT_ROOT%local.properties"

echo.
echo ==^> Building debug APK
call "%PROJECT_ROOT%gradlew.bat" --no-daemon assembleDebug
if errorlevel 1 (
    echo Gradle build failed.
    exit /b 1
)

set "BUILT_APK=%PROJECT_ROOT%app\build\outputs\apk\debug\app-debug.apk"
if not exist "%BUILT_APK%" (
    echo APK not found at %BUILT_APK%
    exit /b 1
)

if not exist "%PROJECT_ROOT%dist" mkdir "%PROJECT_ROOT%dist"
set "OUT_APK=%PROJECT_ROOT%dist\netsocket-notifications-debug.apk"
copy /y "%BUILT_APK%" "%OUT_APK%" >nul

echo.
echo ==^> Installing over ADB
set "ADB=%SDK_PATH%\platform-tools\adb.exe"
if not exist "%ADB%" (
    echo adb.exe not found at %ADB%. Install the SDK platform-tools package.
    exit /b 1
)
set "PKG=com.strayfade.netsocket.notification.debug"
"%ADB%" devices -l
"%ADB%" install -r "%OUT_APK%" > "%TEMP%\ns-install.log" 2>&1
if errorlevel 1 (
    findstr /C:"INSTALL_FAILED_UPDATE_INCOMPATIBLE" "%TEMP%\ns-install.log" >nul
    if errorlevel 1 (
        type "%TEMP%\ns-install.log"
        echo adb install failed. Make sure a device is connected ^(adb devices^) and USB debugging is on.
        exit /b 1
    )
    echo Existing install was signed with a different debug key; reinstalling fresh...
    "%ADB%" uninstall "%PKG%"
    "%ADB%" install "%OUT_APK%"
    if errorlevel 1 (
        echo adb install failed after uninstall.
        exit /b 1
    )
)

echo.
echo ==^> Done: installed %OUT_APK%
